import bookImage from '../../images/livro.png';

export const books = [
  { id: 1, name: 'Harry Potter e a Pedra Filosofal', autor: 'J.K. Rowling', src: bookImage },
  { id: 2, name: '1984', autor: 'George Orwell', src: bookImage },
  { id: 3, name: 'O Senhor dos Anéis: A Sociedade do Anel', autor: 'J.R.R. Tolkien', src: bookImage },
  { id: 4, name: 'Cem Anos de Solidão', autor: 'Gabriel García Márquez', src: bookImage },
  { id: 5, name: 'Dom Quixote', autor: 'Miguel de Cervantes', src: bookImage },
  { id: 6, name: 'O Pequeno Príncipe', autor: 'Antoine de Saint-Exupéry', src: bookImage },
  { id: 7, name: 'A Guerra dos Tronos', autor: 'George R.R. Martin', src: bookImage },
  { id: 8, name: 'O Apanhador no Campo de Centeio', autor: 'J.D. Salinger', src: bookImage },
  { id: 9, name: 'Moby Dick', autor: 'Herman Melville', src: bookImage },
  { id: 10, name: 'A Revolução dos Bichos', autor: 'George Orwell', src: bookImage },
  { id: 11, name: 'O Sol é para Todos', autor: 'Harper Lee', src: bookImage },
  { id: 12, name: 'Grande Sertão: Veredas', autor: 'João Guimarães Rosa', src: bookImage },
  { id: 13, name: 'Crime e Castigo', autor: 'Fyodor Dostoevsky', src: bookImage },
  { id: 14, name: 'A Montanha Mágica', autor: 'Thomas Mann', src: bookImage },
  { id: 15, name: 'Ulisses', autor: 'James Joyce', src: bookImage },
  { id: 16, name: 'O Processo', autor: 'Franz Kafka', src: bookImage },
  { id: 17, name: 'As Aventuras de Huckleberry Finn', autor: 'Mark Twain', src: bookImage },
  { id: 18, name: 'O Som e a Fúria', autor: 'William Faulkner', src: bookImage },
  { id: 19, name: 'Machado de Assis: Obra Completa', autor: 'Machado de Assis', src: bookImage },
  { id: 20, name: 'Crepúsculo', autor: 'Stephenie Meyer', src: bookImage },
  { id: 21, name: 'Orgulho e Preconceito', autor: 'Jane Austen', src: bookImage },
  { id: 22, name: 'O Leão, a Feiticeira e o Guarda-Roupa', autor: 'C.S. Lewis', src: bookImage },
  { id: 23, name: 'Os Miseráveis', autor: 'Victor Hugo', src: bookImage },
  { id: 24, name: 'A Culpa é das Estrelas', autor: 'John Green', src: bookImage },
  { id: 25, name: 'O Retrato de Dorian Gray', autor: 'Oscar Wilde', src: bookImage },
  { id: 26, name: 'O name do Vento', autor: 'Patrick Rothfuss', src: bookImage },
  { id: 27, name: 'O Código Da Vinci', autor: 'Dan Brown', src: bookImage },
  { id: 28, name: 'O Morro dos Ventos Uivantes', autor: 'Emily Brontë', src: bookImage },
  { id: 29, name: 'O Hobbit', autor: 'J.R.R. Tolkien', src: bookImage },
  { id: 30, name: 'O Príncipe', autor: 'Maquiavel', src: bookImage },
  { id: 31, name: 'A Menina que Roubava books', autor: 'Markus Zusak', src: bookImage },
  { id: 32, name: 'Sapiens: Uma Breve História da Humanidade', autor: 'Yuval Noah Harari', src: bookImage },
  { id: 33, name: 'Cemitério Maldito', autor: 'Stephen King', src: bookImage },
  { id: 34, name: 'Assassinato no Expresso do Oriente', autor: 'Agatha Christie', src: bookImage },
  { id: 35, name: 'O Colecionador', autor: 'John Fowles', src: bookImage },
  { id: 36, name: 'O Cão dos Baskervilles', autor: 'Arthur Conan Doyle', src: bookImage },
  { id: 37, name: 'O Velho e o Mar', autor: 'Ernest Hemingway', src: bookImage },
  { id: 38, name: 'O Conde de Monte Cristo', autor: 'Alexandre Dumas', src: bookImage },
  { id: 39, name: 'A Sangue Frio', autor: 'Truman Capote', src: bookImage },
  { id: 40, name: 'Norwegian Wood', autor: 'Haruki Murakami', src: bookImage }
];